#!/bin/bash

#check if directory exists. create if it does not

if [ ! -d ~/.blinkcontrol ]
then
mkdir ~/.blinkcontrol
echo null > ~/.blinkcontrol/blinkauthcode
fi

#prompt for email

echo Please enter your email address

read email

echo $email > ~/.blinkcontrol/blinkcredentials

echo Please enter your blink password

read password

echo $password >> ~/.blinkcontrol/blinkcredentials

echo
echo "Cameras Armed:"
blinkcontrol status
